### PR TITLE
Make tl-parser stable and portable across platforms

### PR DESCRIPTION
**Pull request by cavallium**
- Fix file output for Release builds
- Change assertions to abort, to allow the build to fail on release targets if something goes wrong
- Various bugfixes with assertions in wrong places, and with impossible assertions
- Various bugfixes with if statements without brackets, and with duplicated code
- Change all stderr print to the respective macro
- TL_ERROR
- Fix .gitignore
- Remove m4 leftovers
- Remove autoconf
- Remove makefile
- Rewrite compilation with CMake, tested on Windows, Linux and MacOS X
- Add support for Windows (Port vkext_write, getops, and more to Windows)
- Remove ZLib dependency, restoring crc32.c and crc32.h from an old commit of tl-parser (to make it more portable, since dependency management on Windows is literally the hell)
- Remove unused leftovers from telegram cli (also removed config.h, it was unused)

This fixed version of tl-parser can be used by @levlam and @arseny30 inside tdlib code generation part, to remove the necessity of putting the compiled .tlo binary files by hand on every release. I already tested it by adding the compilation and execution of this new tl-parser into td/generate CMakeLists.txt and it works as expected, generating the three .tlo files needed by tdlib.

### CODE REVIEW

**Comment by BenWiederhake** [comment]
Spoilers: This repo is dead and vysheng has been offline since forever.

You could just copy the code, it's LGPL after all, but before you do: `portable-endian.h` is not portable at all. Have a look at how telegram-purple (which uses tl-parser under the hood) had to change it: https://github.com/majn/tgl/tree/master/tl-parser
If you work towards endian-correctness, you might be interested in this re-implementation, which has absolutely no dependencies, and works on all Endianesses you can think of, including new ones:
https://github.com/BenWiederhake/portable-endian

**Comment by Cavallium** [comment]
Thanks for the suggestion about portable-endian.
By the way I talked with levlam before opening this pull request, so probably it can be merged by arseny30, like the last two commits.

**Comment by Cavallium** [comment]
I looked into tdlib and it doesn't work with big-endian architectures. I will not change portable_endian to avoid breaking things on windows

**Comment by AndreyKostromskoy** [comment]
@BenWiederhake @Cavallium  use this parser https://github.com/VKCOM/kphp/tree/master/common/tl

**Comment by cavallium** [comment]
The other pr was merged. Closing this one.

**Pull request closed without merging**
